package ronsijm.templater.common

enum class ErrorCode {

    PARSE_SYNTAX_ERROR,
    PARSE_UNCLOSED_TAG,
    PARSE_INVALID_EXPRESSION,
    PARSE_UNEXPECTED_TOKEN,


    VALIDATION_MISSING_PARENTHESES,
    VALIDATION_UNKNOWN_MODULE,
    VALIDATION_UNKNOWN_FUNCTION,
    VALIDATION_INVALID_ARGUMENT,
    VALIDATION_TYPE_MISMATCH,


    EXECUTION_COMMAND_FAILED,
    EXECUTION_TIMEOUT,
    EXECUTION_CANCELLED,
    EXECUTION_DIVISION_BY_ZERO,
    EXECUTION_NULL_REFERENCE,
    EXECUTION_INDEX_OUT_OF_BOUNDS,


    IO_FILE_NOT_FOUND,
    IO_PERMISSION_DENIED,
    IO_NETWORK_ERROR,
    IO_CLIPBOARD_ERROR,


    CONFIG_INVALID_SETTING,
    CONFIG_MISSING_REQUIRED,


    INTERNAL_ERROR,
    INTERNAL_NOT_IMPLEMENTED
}

